<div>
  <h2>
    The HPy blogposts
  </h2>
  <div>
    Create a guest post via a PR to the <a href="https://github.com/hpyproject/hpyproject.github.io/">source repo</a>
  </div>
</div>
    <div id="global-recent-posts">
    <h2>
      Recent Posts
    </h2>
    <ul class="post-list">
      <li>
        <a href="/blog/posts/2021/03/hello-hpy/" class="listtitle">Hello, HPy</a>
      </li>
    </ul>
  </div>

          <div id="global-archive-list">
          <h2>
            Archives
          </h2>
          <ul class="archive-level archive-level-1">
            <li><a class="reference" href="/2021/">2021</a> (1)
            </li>
          </ul>
        </div>